services:
  - type: web
    name: stress-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --timeout 120 --bind 0.0.0.0:$PORT
    plan: free
